### ISSUE TITLE
Strange generic

### ISSUE THREAD

**Issue by Alexey-T** [TeamFND/AGPascalTokenizer#1]
Why not to replace Tfpglist(string) with TStringList?

**Comment by Artem3213212** [comment]
Вообще мне нужен тип с методом Contains или подобным но я его в FPC не нашёл поэтому пока поставил этот. Мб ты подскажешь что тут можно применить?

**Comment by Alexey-T** [comment]
TStringList.IndexOf вообще то

**Comment by Artem3213212** [comment]
тогда надо ловить exception а это не производительно

**Comment by Artem3213212** [comment]
а извиняюсь да там -1 а не exception

**Comment by Artem3213212** [comment]
хорошо по правлю как будет время

**Comment by Alexey-T** [comment]
"поправлю" слитно =)
